- id: 1
  type: 'SUCCESS'
  exception: ''
  message: '在庫更新処理が正常に完了しました。'
- id: 2
  type: 'CRAWL_SUCCESS'
  exception: ''
  message: '在庫データのCrawl処理が正常に完了しました。'
- id: 3
  type: 'NOTHING'
  exception: ''
  message: '更新対象のデータがありません。'
- id: 4
  type: 'UNKNOWN_ERROR'
  exception: ''
  message: '想定外のエラーが発生しました。'
- id: 5
  type: 'INIT_ERROR'
  exception: 'InitializeException'
  message: '初期化処理に失敗しました。'
- id: 6
  type: 'DOWNLOAD_ERROR'
  exception: 'DownloadException'
  message: '在庫データのダウンロードに失敗しました。'
- id: 7
  type: 'OLD_FILE_ERROR'
  exception: 'OldFileException'
  message: '最新の在庫データがありませんでした。'
- id: 8
  type: 'SET_STOCK_ERROR'
  exception: 'SetStockException'
  message: '在庫更新データの作成に失敗しました。'
- id: 9
  type: 'OUTPUT_STOCK_ERROR'
  exception: 'OutputStockException'
  message: '在庫更新データの出力に失敗しました。'
- id: 10
  type: 'UPLOAD_ERROR'
  exception: 'UploadException'
  message: '在庫更新データのアップロードに失敗しました。'
- id: 11
  type: 'UPDATE_MASTER_ERROR'
  exception: 'UpdateMasterException'
  message: 'マスターデータの更新に失敗しました'
- id: 12
  type: 'TERMINATE_ERROR'
  exception: 'TerminateException'
  message: 'マスターデータの更新に失敗しました'
- id: 13
  type: 'OUTPUT_CRAWL_ERROR'
  exception: ''
  message: 'Crawlデータの出力に失敗しました。'

